"use server";

import recipesData from "@/mocks/recipes.mock.json";
import { Recipe, RecipePreview } from "@/types/recipes";
import { filterAndScoreRecipes } from "@/lib/utils/recipe-scoring";
import { prisma } from "@/lib/prisma";
// import { Prisma } from "@prisma/client"; // This is kinda to if i need the types generated by prisma build

const recipes: Recipe[] = recipesData;

// --- Mocked Function ---
// export async function getRecipesPreview(
//   query?: string,
//   currentPage?: number,
// ): Promise<RecipePreview[]> {
//   const recipesPreview = recipes
//     .filter((recipe) => ilike(recipe.recipe_name, query))
//     .map<RecipePreview>((recipe) => {
//       return {
//         recipe_id: recipe.recipe_id,
//         recipe_name: recipe.recipe_name,
//         recipe_slug: recipe.recipe_slug,
//         recipe_country: recipe.recipe_country,
//         recipe_image: recipe.recipe_image,
//         creator_name: recipe.creator_name,
//       };
//     });
//
//   return recipesPreview;
// }

// --- Real DB implementation ---
const PAGE_SIZE = 20;

export async function getRecipesPreview(
  query?: string,
  currentPage?: number,
): Promise<RecipePreview[]> {
  const page = currentPage ?? 1;

  const recipes = await prisma.recipe.findMany({
    where: {
      deletedAt: null,
      ...(query && {
        title: { contains: query, mode: "insensitive" },
      }),
    },
    select: {
      id: true,
      title: true,
      slug: true,
      image: true,
      country: { select: { name: true } },
      user: { select: { name: true } },
    },
    skip: (page - 1) * PAGE_SIZE,
    take: PAGE_SIZE,
    orderBy: { createdAt: "desc" },
  });

  return recipes.map((recipe) => ({
    recipe_id: recipe.id,
    recipe_name: recipe.title,
    recipe_slug: recipe.slug,
    recipe_image: recipe.image,
    recipe_country: recipe.country.name,
    creator_name: recipe.user.name ?? "Unknown",
  }));
}

// --- Mocked Function ---
// export async function getRecipeBySlug(slug: string) {
//   const recipe = recipes.find((recipe) => recipe.recipe_slug === slug);
//   return recipe;
// }

// --- Real DB implementation ---
export async function getRecipeBySlug(slug: string): Promise<Recipe | null> {
  const recipe = await prisma.recipe.findFirst({
    where: { slug, deletedAt: null },
    select: {
      id: true,
      title: true,
      slug: true,
      description: true,
      image: true,
      instructions: true,
      userId: true,
      country: { select: { name: true } },
      user: { select: { name: true } },
      recipeIngredients: {
        select: {
          quantity: true,
          unit: true,
          weight: true,
          ingredient: { select: { name: true } },
        },
      },
    },
  });

  if (!recipe) return null;

  return {
    recipe_id: recipe.id,
    recipe_name: recipe.title,
    recipe_slug: recipe.slug,
    recipe_description: recipe.description,
    recipe_image: recipe.image,
    recipe_instructions: recipe.instructions as Recipe["recipe_instructions"],
    recipe_user_id: recipe.userId,
    recipe_country: recipe.country.name,
    creator_name: recipe.user.name ?? "Unknown",
    recipe_ingredients: recipe.recipeIngredients.map((ri) => ({
      name: ri.ingredient.name,
      unit: ri.unit,
      weight: ri.weight,
      quantity: ri.quantity,
    })),
  };
}

// --- Mocked Funcion ---
// export async function getRecipeById(id: string): Promise<Recipe | null> {
//   if (!id || typeof id !== 'string') return null
//   return recipes.find((r) => r.recipe_id === id) ?? null
// }

// --- Real DB implementation ---
export async function getRecipeById(id: string): Promise<Recipe | null> {
  if (!id || typeof id !== "string") return null;

  const recipe = await prisma.recipe.findUnique({
    where: { id, deletedAt: null },
    select: {
      id: true,
      title: true,
      slug: true,
      description: true,
      image: true,
      instructions: true,
      userId: true,
      country: { select: { name: true } },
      user: { select: { name: true } },
      recipeIngredients: {
        select: {
          quantity: true,
          unit: true,
          weight: true,
          ingredient: { select: { name: true } },
        },
      },
    },
  });

  if (!recipe) return null;

  return {
    recipe_id: recipe.id,
    recipe_name: recipe.title,
    recipe_slug: recipe.slug,
    recipe_description: recipe.description,
    recipe_image: recipe.image,
    recipe_instructions: recipe.instructions as Recipe["recipe_instructions"],
    recipe_user_id: recipe.userId,
    recipe_country: recipe.country.name,
    creator_name: recipe.user.name ?? "Unknown",
    recipe_ingredients: recipe.recipeIngredients.map((ri) => ({
      name: ri.ingredient.name,
      unit: ri.unit,
      weight: ri.weight,
      quantity: ri.quantity,
    })),
  };
}

export type SearchResult = {
  recipe_id: string;
  recipe_name: string;
  recipe_slug: string;
  recipe_image: string;
  recipe_country: string;
  creator_name: string;
  score: number;
};

// --- Mocked Funcion ---
// export async function searchRecipesByIngredients(
//   ingredientNames: string[],
// ): Promise<SearchResult[]> {
//   if (ingredientNames.length === 0) return [];
//
//   const recipesForScoring = recipes.map((recipe) => ({
//     id: recipe.recipe_id,
//     title: recipe.recipe_name,
//     ingredients: recipe.recipe_ingredients.map((ing) => ({
//       name: ing.name,
//       weight: ing.weight,
//     })),
//   }));
//
//   const scoredRecipes = filterAndScoreRecipes(
//     recipesForScoring,
//     ingredientNames,
//   );
//
//   return scoredRecipes.flatMap((scored) => {
//     const original = recipes.find((r) => r.recipe_id === scored.id);
//     if (!original) return [];
//     return [
//       {
//         recipe_id: original.recipe_id,
//         recipe_name: original.recipe_name,
//         recipe_slug: original.recipe_slug,
//         recipe_image: original.recipe_image,
//         recipe_country: original.recipe_country,
//         creator_name: original.creator_name,
//         score: Math.round(scored.score * 100),
//       },
//     ];
//   });
// }

// --- Real DB implementation ---
export async function searchRecipesByIngredients(
  ingredientNames: string[],
): Promise<SearchResult[]> {
  if (ingredientNames.length === 0) return [];

  const recipes = await prisma.recipe.findMany({
    where: { deletedAt: null },
    select: {
      id: true,
      title: true,
      slug: true,
      image: true,
      country: { select: { name: true } },
      user: { select: { name: true } },
      recipeIngredients: {
        select: {
          weight: true,
          ingredient: { select: { name: true } },
        },
      },
    },
  });

  const recipesForScoring = recipes.map((recipe) => ({
    id: recipe.id,
    title: recipe.title,
    ingredients: recipe.recipeIngredients.map((ri) => ({
      name: ri.ingredient.name,
      weight: ri.weight,
    })),
  }));

  const scoredRecipes = filterAndScoreRecipes(
    recipesForScoring,
    ingredientNames,
  );

  return scoredRecipes.flatMap((scored) => {
    const original = recipes.find((r) => r.id === scored.id);
    if (!original) return [];
    return [
      {
        recipe_id: original.id,
        recipe_name: original.title,
        recipe_slug: original.slug,
        recipe_image: original.image,
        recipe_country: original.country.name,
        creator_name: original.user.name ?? "Unknown",
        score: Math.round(scored.score * 100),
      },
    ];
  });
}

export async function getRandomRecipeSlug(): Promise<string | null> {
  const count = await prisma.recipe.count({ where: { deletedAt: null } });
  if (count === 0) return null;
  const skip = Math.floor(Math.random() * count);
  const recipe = await prisma.recipe.findFirst({
    where: { deletedAt: null },
    select: { slug: true },
    skip,
  });
  return recipe?.slug ?? null;
}

